font = "pressstart"

background = "#141719"
light_background = "#e7e8e4"
gradient_start = "#8f9876"
gradient_mid = "#aaa27f"
gradient_end = "#788f7a"

char_spacing = 2
word_spacing = 2
line_spacing = 1

shadow = true
shadow_offset_x = 1
shadow_offset_y = 1
shadow_style = "light"

[assets.v]
padding = 20
offset_x = -5
offset_y = -5

[assets.vimcolorschemes]
padding = 40
