package generator

import (
	"bytes"
	"fmt"
	"html"
)

const (
	cellWidth       = 10
	cellHeight      = 18
	cellInset       = 8
	backgroundColor = "#090e13"
	midColor        = "#a88e90"
)

func renderSVG(item asset, cells []cell, cols int, rows int) []byte {
	width := cols*cellWidth + item.Padding*2
	height := rows*cellHeight + item.Padding*2
	translate := item.Padding - cellInset

	var out bytes.Buffer
	fprintf(&out, "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"%d\" height=\"%d\" viewBox=\"0 0 %d %d\" role=\"img\" aria-labelledby=\"title desc\" shape-rendering=\"crispEdges\">\n", width, height, width, height)
	fprintf(&out, "  <title id=\"title\">%s ANSI art</title>\n", html.EscapeString(item.Name))
	fprintf(&out, "  <desc id=\"desc\">Cell-accurate SVG rendering of terminal ANSI art generated by cmd/generate-assets.</desc>\n")
	fprintf(&out, "  <defs>\n")
	fprintf(&out, "    <linearGradient id=\"border-gradient\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\">\n")
	fprintf(&out, "      <stop offset=\"0\" stop-color=\"%s\"/>\n", startColor)
	fprintf(&out, "      <stop offset=\"0.5\" stop-color=\"%s\"/>\n", midColor)
	fprintf(&out, "      <stop offset=\"1\" stop-color=\"%s\"/>\n", endColor)
	fprintf(&out, "    </linearGradient>\n")
	fprintf(&out, "  </defs>\n")
	fprintf(&out, "  <rect width=\"100%%\" height=\"100%%\" fill=\"%s\"/>\n", backgroundColor)
	fprintf(&out, "  <rect x=\"3\" y=\"3\" width=\"%d\" height=\"%d\" fill=\"none\" stroke=\"url(#border-gradient)\" stroke-width=\"2\" opacity=\"0.9\"/>\n", width-6, height-6)
	fprintf(&out, "  <rect x=\"8\" y=\"8\" width=\"%d\" height=\"%d\" fill=\"none\" stroke=\"url(#border-gradient)\" stroke-width=\"1\" opacity=\"0.45\"/>\n", width-16, height-16)
	fprintf(&out, "  <g transform=\"translate(%d %d)\">\n", translate, translate)

	for _, c := range cells {
		opacity := ""
		if c.Opacity != "" {
			opacity = fmt.Sprintf(` opacity="%s"`, c.Opacity)
		}
		fprintf(&out, "    <rect x=\"%d\" y=\"%d\" width=\"%d\" height=\"%d\" fill=\"%s\"%s/>\n", c.X*cellWidth+cellInset, c.Y*cellHeight+cellInset, cellWidth, cellHeight, c.Color, opacity)
	}

	fprintf(&out, "  </g>\n")
	fprintf(&out, "</svg>\n")
	return out.Bytes()
}

func fprintf(out *bytes.Buffer, format string, args ...any) {
	_, _ = fmt.Fprintf(out, format, args...)
}
