package generator

import (
	"bytes"
	"fmt"
	"html"
)

const (
	cellWidth  = 10
	cellHeight = 18
	cellInset  = 8
)

func renderSVG(item asset, theme theme, cells []cell, cols int, rows int) []byte {
	layout := assetLayout(item, cells, cols, rows)
	translateX := layout.OffsetX - cellInset
	translateY := layout.OffsetY - cellInset

	var out bytes.Buffer
	fprintf(&out, "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"%d\" height=\"%d\" viewBox=\"0 0 %d %d\" role=\"img\" aria-labelledby=\"title desc\" shape-rendering=\"crispEdges\">\n", layout.Width, layout.Height, layout.Width, layout.Height)
	fprintf(&out, "  <title id=\"title\">%s ANSI art</title>\n", html.EscapeString(item.Name))
	fprintf(&out, "  <desc id=\"desc\">Cell-accurate SVG rendering of terminal ANSI art generated by cmd/generate-assets.</desc>\n")
	if item.Border {
		fprintf(&out, "  <defs>\n")
		fprintf(&out, "    <linearGradient id=\"border-gradient\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\">\n")
		fprintf(&out, "      <stop offset=\"0\" stop-color=\"%s\"/>\n", theme.GradientStart)
		fprintf(&out, "      <stop offset=\"0.5\" stop-color=\"%s\"/>\n", theme.GradientMid)
		fprintf(&out, "      <stop offset=\"1\" stop-color=\"%s\"/>\n", theme.GradientEnd)
		fprintf(&out, "    </linearGradient>\n")
		fprintf(&out, "  </defs>\n")
	}
	fprintf(&out, "  <rect width=\"100%%\" height=\"100%%\" fill=\"%s\"/>\n", theme.Background)
	if item.Border {
		fprintf(&out, "  <rect x=\"1\" y=\"1\" width=\"%d\" height=\"%d\" fill=\"none\" stroke=\"url(#border-gradient)\" stroke-width=\"2\" opacity=\"0.9\"/>\n", layout.Width-2, layout.Height-2)
		fprintf(&out, "  <rect x=\"5\" y=\"5\" width=\"%d\" height=\"%d\" fill=\"none\" stroke=\"url(#border-gradient)\" stroke-width=\"1\" opacity=\"0.45\"/>\n", layout.Width-10, layout.Height-10)
	}
	fprintf(&out, "  <g transform=\"translate(%d %d)\">\n", translateX, translateY)

	for _, c := range cells {
		opacity := ""
		if c.Opacity != "" {
			opacity = fmt.Sprintf(` opacity="%s"`, c.Opacity)
		}
		fprintf(&out, "    <rect x=\"%d\" y=\"%d\" width=\"%d\" height=\"%d\" fill=\"%s\"%s/>\n", c.X*cellWidth+cellInset, c.Y*cellHeight+cellInset, cellWidth, cellHeight, c.Color, opacity)
	}

	fprintf(&out, "  </g>\n")
	fprintf(&out, "</svg>\n")
	return out.Bytes()
}

func fprintf(out *bytes.Buffer, format string, args ...any) {
	_, _ = fmt.Fprintf(out, format, args...)
}

type assetRenderLayout struct {
	Width   int
	Height  int
	OffsetX int
	OffsetY int
}

func assetLayout(item asset, cells []cell, cols int, rows int) assetRenderLayout {
	contentWidth := cols * cellWidth
	contentHeight := rows * cellHeight
	width := contentWidth + item.Padding*2
	height := contentHeight + item.Padding*2
	if item.Square {
		width = max(width, height)
		height = width
	}
	offsetX := (width - contentWidth) / 2
	offsetY := (height - contentHeight) / 2
	if item.Square {
		minX, maxX, hasX := frontCellBounds(cells, true)
		minY, maxY, hasY := frontCellBounds(cells, false)
		offsetX = centeredOffset(width, contentWidth, cellWidth, minX, maxX, hasX)
		offsetY = centeredOffset(height, contentHeight, cellHeight, minY, maxY, hasY)
	}

	return assetRenderLayout{
		Width:   width,
		Height:  height,
		OffsetX: offsetX + item.OffsetX,
		OffsetY: offsetY + item.OffsetY,
	}
}

func centeredOffset(size int, contentSize int, cellSize int, minCell int, maxCell int, ok bool) int {
	if !ok {
		return (size - contentSize) / 2
	}

	frontSize := (maxCell - minCell + 1) * cellSize
	return (size-frontSize)/2 - minCell*cellSize
}

func frontCellBounds(cells []cell, horizontal bool) (int, int, bool) {
	minCell := 0
	maxCell := 0
	found := false
	for _, c := range cells {
		if c.Opacity != "" {
			continue
		}

		value := c.Y
		if horizontal {
			value = c.X
		}
		if !found || value < minCell {
			minCell = value
		}
		if !found || value > maxCell {
			maxCell = value
		}
		found = true
	}
	return minCell, maxCell, found
}
