package generator

import (
	"bytes"
	"fmt"
	"html"
	"math"
)

const (
	cellWidth  = 10
	cellHeight = 18
	cellInset  = 8
)

func renderSVG(item asset, theme theme, cells []cell, cols int, rows int) []byte {
	if item.OpenGraph {
		return renderOpenGraphSVG(item, theme, cells, cols, rows)
	}

	layout := assetLayout(item, cells, cols, rows)
	translateX := layout.OffsetX - cellInset
	translateY := layout.OffsetY - cellInset

	var out bytes.Buffer
	fprintf(&out, "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"%d\" height=\"%d\" viewBox=\"0 0 %d %d\" role=\"img\" aria-labelledby=\"title desc\" shape-rendering=\"crispEdges\">\n", layout.Width, layout.Height, layout.Width, layout.Height)
	fprintf(&out, "  <title id=\"title\">%s ANSI art</title>\n", html.EscapeString(item.Name))
	fprintf(&out, "  <desc id=\"desc\">Cell-accurate SVG rendering of terminal ANSI art generated by cmd/generate-assets.</desc>\n")
	if item.Border {
		fprintf(&out, "  <defs>\n")
		fprintf(&out, "    <linearGradient id=\"border-gradient\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\">\n")
		fprintf(&out, "      <stop offset=\"0\" stop-color=\"%s\"/>\n", theme.GradientStart)
		fprintf(&out, "      <stop offset=\"0.5\" stop-color=\"%s\"/>\n", theme.GradientMid)
		fprintf(&out, "      <stop offset=\"1\" stop-color=\"%s\"/>\n", theme.GradientEnd)
		fprintf(&out, "    </linearGradient>\n")
		fprintf(&out, "  </defs>\n")
	}
	if !item.Transparent {
		fprintf(&out, "  <rect width=\"100%%\" height=\"100%%\" fill=\"%s\"/>\n", assetBackground(item, theme))
	}
	if item.Border {
		border := borderMetrics(item)
		fprintf(&out, "  <rect x=\"%d\" y=\"%d\" width=\"%d\" height=\"%d\" fill=\"none\" stroke=\"url(#border-gradient)\" stroke-width=\"%d\" opacity=\"0.9\"/>\n", border.OuterOffset, border.OuterOffset, layout.Width-border.OuterStroke, layout.Height-border.OuterStroke, border.OuterStroke)
		fprintf(&out, "  <rect x=\"%d\" y=\"%d\" width=\"%d\" height=\"%d\" fill=\"none\" stroke=\"url(#border-gradient)\" stroke-width=\"%d\" opacity=\"0.45\"/>\n", border.InnerInset, border.InnerInset, layout.Width-border.InnerInset*2, layout.Height-border.InnerInset*2, border.InnerStroke)
	}
	fprintf(&out, "  <g transform=\"translate(%d %d)\">\n", translateX, translateY)

	for _, c := range cells {
		opacity := ""
		if c.Opacity != "" {
			opacity = fmt.Sprintf(` opacity="%s"`, c.Opacity)
		}
		fprintf(&out, "    <rect x=\"%d\" y=\"%d\" width=\"%d\" height=\"%d\" fill=\"%s\"%s/>\n", c.X*cellWidth+cellInset, c.Y*cellHeight+cellInset, cellWidth, cellHeight, c.Color, opacity)
	}

	fprintf(&out, "  </g>\n")
	fprintf(&out, "</svg>\n")
	return out.Bytes()
}

func renderOpenGraphSVG(item asset, theme theme, cells []cell, cols int, rows int) []byte {
	width := item.Width
	height := item.Height
	if width == 0 || height == 0 {
		layout := assetLayout(item, cells, cols, rows)
		width = layout.Width
		height = layout.Height
	}

	contentWidth := cols * cellWidth
	contentHeight := rows * cellHeight
	scale := math.Min(0.38, float64(width-220)/float64(contentWidth))
	logoWidth := float64(contentWidth) * scale
	logoHeight := float64(contentHeight) * scale
	logoX := (float64(width) - logoWidth) / 2
	logoY := (float64(height) - logoHeight) / 2
	panelPaddingX := 44.0
	panelPaddingY := 36.0
	panelX := logoX - panelPaddingX
	panelY := logoY - panelPaddingY
	panelWidth := logoWidth + panelPaddingX*2
	panelHeight := logoHeight + panelPaddingY*2

	var out bytes.Buffer
	fprintf(&out, "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"%d\" height=\"%d\" viewBox=\"0 0 %d %d\" role=\"img\" aria-labelledby=\"title desc\" shape-rendering=\"crispEdges\">\n", width, height, width, height)
	fprintf(&out, "  <title id=\"title\">%s Open Graph image</title>\n", html.EscapeString(item.Name))
	fprintf(&out, "  <desc id=\"desc\">Open Graph image for vimcolorschemes generated by cmd/generate-assets.</desc>\n")
	fprintf(&out, "  <defs>\n")
	fprintf(&out, "    <linearGradient id=\"border-gradient\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\">\n")
	fprintf(&out, "      <stop offset=\"0\" stop-color=\"%s\"/>\n", theme.GradientStart)
	fprintf(&out, "      <stop offset=\"0.5\" stop-color=\"%s\"/>\n", theme.GradientMid)
	fprintf(&out, "      <stop offset=\"1\" stop-color=\"%s\"/>\n", theme.GradientEnd)
	fprintf(&out, "    </linearGradient>\n")
	fprintf(&out, "    <filter id=\"soft-blur\"><feGaussianBlur stdDeviation=\"6\"/></filter>\n")
	fprintf(&out, "  </defs>\n")
	fprintf(&out, "  <rect width=\"100%%\" height=\"100%%\" fill=\"%s\"/>\n", assetBackground(item, theme))
	fprintf(&out, "  <g opacity=\"1\" filter=\"url(#soft-blur)\">\n")
	writeOpenGraphCards(&out)
	fprintf(&out, "  </g>\n")
	fprintf(&out, "  <rect x=\"%.1f\" y=\"%.1f\" width=\"%.1f\" height=\"%.1f\" fill=\"%s\" opacity=\"0.82\"/>\n", panelX, panelY, panelWidth, panelHeight, assetBackground(item, theme))
	fprintf(&out, "  <rect x=\"%.1f\" y=\"%.1f\" width=\"%.1f\" height=\"%.1f\" fill=\"none\" stroke=\"url(#border-gradient)\" stroke-width=\"3\" opacity=\"0.8\"/>\n", panelX, panelY, panelWidth, panelHeight)
	fprintf(&out, "  <g transform=\"translate(%.2f %.2f) scale(%.4f)\">\n", logoX-float64(cellInset)*scale, logoY-float64(cellInset)*scale, scale)
	for _, c := range cells {
		opacity := ""
		if c.Opacity != "" {
			opacity = fmt.Sprintf(` opacity="%s"`, c.Opacity)
		}
		fprintf(&out, "    <rect x=\"%d\" y=\"%d\" width=\"%d\" height=\"%d\" fill=\"%s\"%s/>\n", c.X*cellWidth+cellInset, c.Y*cellHeight+cellInset, cellWidth, cellHeight, c.Color, opacity)
	}
	fprintf(&out, "  </g>\n")
	if item.Label != "" {
		fprintf(&out, "  <text x=\"600\" y=\"455\" text-anchor=\"middle\" fill=\"%s\" opacity=\"0.92\" font-family=\"ui-monospace, SFMono-Regular, Menlo, Consolas, monospace\" font-size=\"34\" letter-spacing=\"4\">%s</text>\n", theme.GradientMid, html.EscapeString(item.Label))
	}
	fprintf(&out, "</svg>\n")
	return out.Bytes()
}

func writeOpenGraphCards(out *bytes.Buffer) {
	cards := openGraphCards()
	lines := openGraphCodeLines()

	for cardIndex, card := range cards {
		fprintf(out, "    <rect x=\"%d\" y=\"%d\" width=\"%d\" height=\"%d\" fill=\"%s\"/>\n", card.X, card.Y, card.Width, card.Height, card.Bg)
		fprintf(out, "    <rect x=\"%d\" y=\"%d\" width=\"%d\" height=\"%d\" fill=\"none\" stroke=\"%s\" stroke-width=\"2\" opacity=\"0.75\"/>\n", card.X+1, card.Y+1, card.Width-2, card.Height-2, card.Border)
		fprintf(out, "    <text x=\"%d\" y=\"%d\" fill=\"%s\" font-family=\"monospace\" font-size=\"12\">%s</text>\n", card.X+18, card.Y+28, card.Border, html.EscapeString(card.Name))
		for i := 0; i < 7; i++ {
			line := truncateOpenGraphCodeLine(lines[(cardIndex*3+i)%len(lines)], card.Width)
			y := card.Y + 56 + i*19
			if y > card.Y+card.Height-18 {
				break
			}
			fprintf(out, "    <text x=\"%d\" y=\"%d\" fill=\"%s\" font-family=\"monospace\" font-size=\"12\">%s</text>\n", card.X+18, y, card.Palette[i%len(card.Palette)], html.EscapeString(line))
		}
	}
}

type assetBorderMetrics struct {
	OuterStroke int
	OuterOffset int
	InnerStroke int
	InnerInset  int
}

func borderMetrics(item asset) assetBorderMetrics {
	scale := item.BorderScale
	if scale < 1 {
		scale = 1
	}
	return assetBorderMetrics{
		OuterStroke: 2 * scale,
		OuterOffset: scale,
		InnerStroke: scale,
		InnerInset:  5 * scale,
	}
}

func fprintf(out *bytes.Buffer, format string, args ...any) {
	_, _ = fmt.Fprintf(out, format, args...)
}

type assetRenderLayout struct {
	Width   int
	Height  int
	OffsetX int
	OffsetY int
}

func assetLayout(item asset, cells []cell, cols int, rows int) assetRenderLayout {
	contentWidth := cols * cellWidth
	contentHeight := rows * cellHeight
	width := contentWidth + item.Padding*2
	height := contentHeight + item.Padding*2
	if item.Width > 0 {
		width = item.Width
	}
	if item.Height > 0 {
		height = item.Height
	}
	if item.Square {
		width = max(width, height)
		height = width
	}
	offsetX := (width - contentWidth) / 2
	offsetY := (height - contentHeight) / 2
	if item.Square {
		minX, maxX, hasX := frontCellBounds(cells, true)
		minY, maxY, hasY := frontCellBounds(cells, false)
		offsetX = centeredOffset(width, contentWidth, cellWidth, minX, maxX, hasX)
		offsetY = centeredOffset(height, contentHeight, cellHeight, minY, maxY, hasY)
	}

	return assetRenderLayout{
		Width:   width,
		Height:  height,
		OffsetX: offsetX + item.OffsetX,
		OffsetY: offsetY + item.OffsetY,
	}
}

func centeredOffset(size int, contentSize int, cellSize int, minCell int, maxCell int, ok bool) int {
	if !ok {
		return (size - contentSize) / 2
	}

	frontSize := (maxCell - minCell + 1) * cellSize
	return (size-frontSize)/2 - minCell*cellSize
}

func frontCellBounds(cells []cell, horizontal bool) (int, int, bool) {
	minCell := 0
	maxCell := 0
	found := false
	for _, c := range cells {
		if c.Opacity != "" {
			continue
		}

		value := c.Y
		if horizontal {
			value = c.X
		}
		if !found || value < minCell {
			minCell = value
		}
		if !found || value > maxCell {
			maxCell = value
		}
		found = true
	}
	return minCell, maxCell, found
}
