package generator

import (
	"strings"
	"testing"
)

func TestRenderSVGUsesComputedDimensionsAndMetadata(t *testing.T) {
	svg := string(renderSVG(asset{Name: "unit<asset>", Padding: 20}, []cell{
		{X: 0, Y: 0, Color: "#010203"},
		{X: 1, Y: 0, Color: "#040506", Opacity: shadowOpacity},
	}, 2, 1))

	wants := []string{
		`width="60" height="58" viewBox="0 0 60 58"`,
		`<title id="title">unit&lt;asset&gt; ANSI art</title>`,
		`generated by cmd/generate-assets`,
		`<rect x="1" y="1" width="58" height="56" fill="none" stroke="url(#border-gradient)" stroke-width="2" opacity="0.9"/>`,
		`<rect x="5" y="5" width="50" height="48" fill="none" stroke="url(#border-gradient)" stroke-width="1" opacity="0.45"/>`,
		`<g transform="translate(12 12)">`,
		`<rect x="8" y="8" width="10" height="18" fill="#010203"/>`,
		`<rect x="18" y="8" width="10" height="18" fill="#040506" opacity="0.42"/>`,
	}
	for _, want := range wants {
		if !strings.Contains(svg, want) {
			t.Fatalf("SVG does not contain %q\n%s", want, svg)
		}
	}
	if strings.Contains(svg, ".sh") {
		t.Fatalf("SVG still references removed shell scripts:\n%s", svg)
	}
}

func TestRenderSVGSquareAssetUsesEqualDimensionsAndCentersContent(t *testing.T) {
	svg := string(renderSVG(asset{Name: "unit", Padding: 20, Square: true}, []cell{
		{X: 0, Y: 0, Color: "#010203"},
	}, 2, 1))

	wants := []string{
		`width="60" height="60" viewBox="0 0 60 60"`,
		`<g transform="translate(12 13)">`,
	}
	for _, want := range wants {
		if !strings.Contains(svg, want) {
			t.Fatalf("SVG does not contain %q\n%s", want, svg)
		}
	}
}
