package generator

import (
	"strings"
	"testing"
)

func TestRenderSVGUsesComputedDimensionsAndMetadata(t *testing.T) {
	svg := string(renderSVG(asset{Name: "unit<asset>", Padding: 20}, []cell{
		{X: 0, Y: 0, Color: "#010203"},
		{X: 1, Y: 0, Color: "#040506", Opacity: shadowOpacity},
	}, 2, 1))

	wants := []string{
		`width="60" height="58" viewBox="0 0 60 58"`,
		`<title id="title">unit&lt;asset&gt; ANSI art</title>`,
		`generated by cmd/generate-assets`,
		`<g transform="translate(12 12)">`,
		`<rect x="8" y="8" width="10" height="18" fill="#010203"/>`,
		`<rect x="18" y="8" width="10" height="18" fill="#040506" opacity="0.42"/>`,
	}
	for _, want := range wants {
		if !strings.Contains(svg, want) {
			t.Fatalf("SVG does not contain %q\n%s", want, svg)
		}
	}
	if strings.Contains(svg, ".sh") {
		t.Fatalf("SVG still references removed shell scripts:\n%s", svg)
	}
}
